name: cling-wash
on:
  push:

jobs:
  a:
    runs-on: ubuntu-18.04
    steps: 
      - run: echo a

  b:
    needs: a
    runs-on: ubuntu-18.04
    steps: 
      - run: echo b

  c:
    needs: b
    runs-on: ubuntu-18.04
    steps: 
      - run: echo c